### ISSUE TITLE
New user not created

### ISSUE THREAD

**Issue by MakarkinPRO** [YanikPei/wp-jwt-authentication#6]
New user not created. What is wrong?

**Comment by MakarkinPRO** [comment]
I'm using NGINX. Just saw that issue:
<br />
<b>Fatal error</b>:  Call to undefined method Requests_Response::is_redirect() in <b>/var/www/wp-includes/class-requests.php</b> on line <b>685</b><br />

**Comment by MakarkinPRO** [comment]
Tried your DEV version, see that issue:

Fatal error: Uncaught exception 'Error' with message 'Please execute `composer install` in /var/www/wp-content/plugins/wp-jwt-authentication-development/ and try again! | ' in /var/www/wp-content/plugins/wp-jwt-authentication-development/wp-authentication-kit.php:21 Stack trace: #0 /var/www/wp-admin/includes/plugin.php(1943): include() #1 /var/www/wp-admin/plugins.php(164): plugin_sandbox_scrape('wp-jwt-authenti...') #2 {main} thrown in /var/www/wp-content/plugins/wp-jwt-authentication-development/wp-authentication-kit.php on line 21

ps: wordpres version 4.6.1

**Comment by YanikPei** [comment]
The first error you mentioned has something to do with the WP-core libraries, which changed in version 4.6. I fixed this issue in the dev-version.

This git-repo is not a out-of-the-box usable WP-plugin. You have to install the dependencies via composer first.
If you do not have composer installed on your computer, you can use the plugin attached. I downloaded the dependencies for you (dev-version).

[wp-jwt-authentication-development.zip](https://github.com/YanikPei/wp-jwt-authentication/files/604745/wp-jwt-authentication-development.zip)

**Comment by MakarkinPRO** [comment]
Yeah! Look like its start working. But is it possible to create a user without type login/password details? Just a phone number?

**Comment by MakarkinPRO** [comment]
I see that issue: wp-login.php?error=true&msg=No+user+matching+the+account+kit+id+was+found (my login and password fields is Blank right?)

**Comment by MakarkinPRO** [comment]
It's working! Thx! I figure that out!

**Comment by YanikPei** [comment]
You can use [AccountKit](https://www.accountkit.com/). Just set up a facebook developer account, activate accountkit. Then enter the credentials in wordpress [(wiki)](https://github.com/YanikPei/wp-jwt-authentication/wiki/Set-up-AccountKit)

**Comment by YanikPei** [comment]
Awesome! Glad I could help!

**Comment by MakarkinPRO** [comment]
Am I need to activate that functions on the FB side for security? http://screencast.com/t/msSXvFgNrnc

**Comment by YanikPei** [comment]
No, you should deactivate both options.

**Comment by MakarkinPRO** [comment]
Thx!
